### ISSUE TITLE
Version 0.7.0 appears completely broken for me

### ISSUE THREAD

**Issue by thecrazy** [willnode/MeshDebugger#2]
All the labels for the vertex, triangle or surface appear at the 0,0,0 local coordinate of the object and are all over each other instead of at each vertex/triangle/surface etc

Also are the counts being done correctly?

I see duplicate vertices on my models but my 3D artist (20 years+ experience in the business) says there are no duplicate vertices in the model he could find using 3DSMAX or Blender.

Any idea what is going on?

**Comment by willnode** [comment]
Wow, sorry been taking so long.

> Also are the counts being done correctly?

Yes, it's what appears in Unity Mesh API.

> I see duplicate vertices on my models but my 3D artist (20 years+ experience in the business) says there are no duplicate vertices in the model he could find using 3DSMAX or Blender.

Yes when you're exporting a 3D model into unity, it get converted into FBX. During that conversion duplication happens because mesh data is triangulated and saved into individual vertexes, not faces. 

---

Closing as it's a question.

**Comment by thecrazy** [comment]
Ok I understand but isn't that a little confusing?

Some of our scripts use vertex positions, I was hoping to be able to check meshes for duplicate / unwelded vertices withing unity but it seems impossible when displayed that way.

For example, in this picture some corners have a weird amount of vertex. There's one at 0? https://github.com/willnode/MeshDebugger/blob/master/Screenshots/Maps.png

**Comment by willnode** [comment]
> Some of our scripts use vertex positions, I was hoping to be able to check meshes for duplicate / unwelded vertices withing unity but it seems impossible when displayed that way.

There's difference between "Shared" and "Duplicate" vertex. Ideally all vertices should have amount of one (or two, for quads) for each, unless you have your own reason to. Again, duplication is normal, as I stated before. If you really one to check your mesh for vertex duplication, do check from your mesh editor (Blender, Maya, etc.) not from unity.

> For example, in this picture some corners have a weird amount of vertex. There's one at 0?

No, it's a vertex index. Programmers count from zero.

**Comment by thecrazy** [comment]
OH  yes, we do indeed HaHaHa!!!

Thanks for the reply!
