### ISSUE TITLE
Change target Transform and Mesh Runtime

### ISSUE THREAD

**Issue by orangeagain** [willnode/MeshDebugger#3]
I generate mesh Runtime. when I use meshdebugger, I drag transform everytime.
Can I set target in code?

**Comment by willnode** [comment]
You mean to disable auto selection? You may can do that by [commenting this line](https://github.com/willnode/MeshDebugger/blob/cb2cc979fa92cd1d72510c2d15c19df6117fcd71/Assets/Plugins/MeshDebugger/Editor/MeshDebugger.cs#L70)

**Comment by orangeagain** [comment]
> You mean to disable auto selection? You may can do that by [commenting this line](https://github.com/willnode/MeshDebugger/blob/cb2cc979fa92cd1d72510c2d15c19df6117fcd71/Assets/Plugins/MeshDebugger/Editor/MeshDebugger.cs#L70)

thank you to reply.
I find a way to set target by click.
good tools!
